---
title: "World Date"
author: "Bongani Mbigi, Daniel Stroe, Cortney Thomas, Jacob, Kurt Kranz"
output:
  html_notebook:
    code_folding: hide
    toc: true
    toc_depth: 4
    toc_float: true
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
require(data.world)
library(class)
require(data.world)
require(ggplot2)
require(MASS)

data.world::set_config(cfg_env("DW_API"))
knitr::opts_chunk$set(echo = TRUE)
```
  
## **R Session Info**  

```{r}
sessionInfo()
```

## **Github Link** 

[Bongani's Github](https://github.com/bongani-m/f17daproject2-mbigi-stroe-kranz-thomas-rodenbusch)

## **Connecting to data.world** 
```{r}
project <- "https://data.world/cct685/bank-marketing"
df <- data.world::query(
  data.world::qry_sql("SELECT * FROM banking_data"),
  dataset = project)
```

## **K Nearest Neighbors** 
This is hte K nearest Neighbors

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

```{r}
Xy=cbind(df$balance,df$duration)
bank.knntrain=df$month != "jun"
knn.pred=knn(Xy[bank.knntrain,],Xy[!bank.knntrain,],df$y[bank.knntrain],k=1)
table(knn.pred,df$y[!bank.knntrain])
mean(knn.pred==df$y[!bank.knntrain])

```


## linear discriminant analysis
```{r}
bank.ldasubset <- sample(1:150, 75)
lda.fit=lda(y~balance+duration,data=df, subset= bank.ldasubset)
lda.fit

renderPlot({
  plot(lda.fit)
})
bank.ldatrain=subset(df,df$month=="jun")
bank.ldapredict = predict(lda.fit, df[-bank.ldasubset, ])
data.frame(bank.ldapredict)[1:5,]
dflda = data.frame(bank.ldapredict)
lda.class = predict(lda.fit, bank.ldatrain)
table(lda.class$class,bank.ldatrain$y)
mean(lda.class$class==bank.ldatrain$y)
```


## quadratic discriminant analysis
```{r}
bank.qdasubset=df$month != "jun"
qda.fit = qda(y~balance+duration, data = df, subset=bank.qdasubset)
qda.fit # Notice - no coeficients.
bank.qdatrain = subset(df, month == "jun")
bank.qdapredict = predict(qda.fit, df[-bank.qdasubset, ])
data.frame(bank.qdapredict)[1:5,]
dfqda = data.frame(bank.qdapredict)
data.frame(bank.qdatrain)[1:5,]
qda.class = predict(qda.fit, bank.qdatrain)
table(qda.class$class,bank.qdatrain$y)
mean(qda.class$class==bank.qdatrain$y)
```